In [9]:
### MCQ300A      #近亲心脏病
### MCQ300C      #近亲糖尿病
### MCQ220       #是否有被告知有癌症
### MCQ160C      #是否有冠心病   #1有 2没有
### MCQ160F      #中风          #1有 2没有

import pandas as pd
import numpy as np

In [10]:
medical_conditions_df = pd.read_sas('E:/work/Paper/NHANES/0708Analysis Data/Medical Conditions/MCQ_E.XPT')

In [14]:
medical_conditions_extract_features = [
    'SEQN',
    'MCQ300A',      #近亲心脏病
    'MCQ300C',      #近亲糖尿病
    'MCQ220',       #癌症
    'MCQ160C',      #冠心病
    'MCQ160F',      #中风
]
medical_conditions_extract_df = medical_conditions_df[medical_conditions_extract_features]
medical_conditions_extract_df['MCQ300A'].replace([7,9], np.nan, inplace=True)
medical_conditions_extract_df['MCQ300C'].replace([7,9], np.nan, inplace=True)
medical_conditions_extract_df['MCQ220'].replace([7,9, np.nan], np.nan, inplace=True)
medical_conditions_extract_df['MCQ160C'].replace([7,9, np.nan], 2, inplace=True)
medical_conditions_extract_df['MCQ160F'].replace([7,9, np.nan], 2, inplace=True)

C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medical_conditions_extract_df['MCQ300A'].replace([7,9], np.nan, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medical_conditions_extract_df['MCQ300A'].replace([7,9], np.nan, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medical_conditions_extract_df['MCQ300C'].replace([7,9], np.nan, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medical_conditions_extract_df['MCQ300C'].replace([7,9], np.nan, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medical_conditions_extract_df['MCQ220'].replace([7,9, np.nan], np.nan, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medical_conditions_extract_df['MCQ220'].replace([7,9, np.nan], np.nan, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medical_conditions_extract_df['MCQ160C'].replace([7,9, np.nan], 2, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medical_conditions_extract_df['MCQ160C'].replace([7,9, np.nan], 2, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  medical_conditions_extract_df['MCQ160F'].replace([7,9, np.nan], 2, inplace=True)
C:\Users\Star\AppData\Local\Temp\ipykernel_5280\2594978108.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  medical_conditions_extract_df['MCQ160F'].replace([7,9, np.nan], 2, inplace=True)

In [15]:
medical_conditions_extract_df

         SEQN  MCQ300A  MCQ300C  MCQ220  MCQ160C  MCQ160F
0     41475.0      2.0      1.0     2.0      2.0      2.0
1     41476.0      NaN      NaN     NaN      2.0      2.0
2     41477.0      2.0      2.0     2.0      2.0      2.0
3     41478.0      NaN      NaN     NaN      2.0      2.0
4     41479.0      2.0      2.0     2.0      2.0      2.0
...       ...      ...      ...     ...      ...      ...
9661  51619.0      2.0      1.0     2.0      2.0      2.0
9662  51620.0      2.0      2.0     2.0      2.0      2.0
9663  51621.0      NaN      NaN     NaN      2.0      2.0
9664  51622.0      2.0      2.0     2.0      2.0      2.0
9665  51623.0      1.0      2.0     2.0      1.0      2.0

[9666 rows x 6 columns]

In [16]:
medical_conditions_extract_df.to_excel('E:/work/Paper/NHANES/0708Analysis Data/Final data/medical_conditions.xlsx')